# Generated by Django 3.1 on 2021-01-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClearedOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('itemSN', models.CharField(max_length=50)),
                ('cleared', models.BooleanField(default=False)),
                ('clearedDate', models.DateField(auto_now=True)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentOwner', models.CharField(max_length=100)),
                ('itemDesc', models.CharField(max_length=50)),
                ('itemSN', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('pcModel', models.CharField(max_length=50)),
                ('osVer', models.CharField(max_length=50)),
                ('ram', models.IntegerField()),
                ('cpu', models.CharField(max_length=50)),
                ('activated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=50)),
            ],
        ),
    ]
