# Generated by Django 3.1 on 2021-01-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClearedShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=50)),
                ('itemSN', models.CharField(max_length=50)),
                ('cleared', models.BooleanField(default=False)),
                ('clearedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShopStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentOwner', models.CharField(max_length=100)),
                ('currentLocation', models.CharField(max_length=50)),
                ('itemDesc', models.CharField(max_length=50)),
                ('itemSN', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
    ]
