# Generated by Django 3.1 on 2021-01-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=50)),
                ('sim_use', models.CharField(default='Data', max_length=50)),
                ('sn', models.CharField(max_length=50)),
                ('phone_num', models.CharField(default=0, max_length=50)),
                ('puk1', models.CharField(max_length=50)),
                ('puk2', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='shopstock',
            name='itemFunc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
